name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  static-analysis-phpstan:
    name: "Static Analysis with PHPStan"
    uses: "doctrine/.github/.github/workflows/static-analysis.yml@1.4.1"
